# Pandas Day 1: Introduction to Pandas DataFrames

## Overview
This Jupyter notebook provides a beginner-friendly introduction to working with Pandas DataFrames in Python. We'll explore basic operations such as loading data from a CSV file, inspecting the data, and understanding its structure. The dataset used is a sample student records file containing information about students' academic performance, placements, and other details.

## Prerequisites
- Python 3.x
- Pandas library (`pip install pandas`)
- Jupyter Notebook or JupyterLab

## Dataset
The dataset (`Dataset/student.csv`) contains student information including ID, name, academic details, and placement status.

## 1. Importing Pandas
Pandas is a powerful data manipulation library in Python that provides data structures like DataFrames for handling tabular data.

In [2]:
import pandas as pd

## 2. Specifying the Data File Path
We define the path to our CSV file. The file is located in the `Dataset` subdirectory relative to the notebook.

In [10]:
data = 'Dataset/student.csv'

## 3. Loading the Data into a DataFrame
- `pd.read_csv(data)` reads the CSV file and creates a DataFrame object.
- `df` is the variable name we assign to our DataFrame.
- Displaying `df` shows the entire DataFrame in the output.

In [11]:
df = pd.read_csv(data)
df

,Student_ID,Name,Gender,Age,Department,City,Attendance_Percentage,Math_Marks,Science_Marks,English_Marks,Python_Marks,Projects_Completed,Internship,Placement_Status,Study_Hours_Per_Day,Backlogs,CGPA,Scholarship,Joining_Date
0,101,Aarav,Male,20,Data Science,Chennai,92,88,91,85,95,4,Yes,Placed,5,0,8.9,Yes,2024-06-12
1,102,Diya,Female,21,AI & ML,Bangalore,85,76,80,79,82,3,No,Not Placed,4,1,7.5,No,2024-06-15
2,103,Vihaan,Male,22,Cyber Security,Hyderabad,78,69,72,70,65,2,Yes,Placed,3,2,6.8,No,2024-06-18
3,104,Ananya,Female,20,Data Science,Mumbai,96,95,93,90,98,5,Yes,Placed,6,0,9.5,Yes,2024-06-20
4,105,Arjun,Male,23,Cloud Computing,Pune,70,60,65,58,62,1,No,Not Placed,2,3,6.1,No,2024-06-25
5,106,Saanvi,Female,21,AI & ML,Delhi,89,84,86,88,90,4,Yes,Placed,5,0,8.7,Yes,2024-06-27
6,107,Krish,Male,22,Data Science,Chennai,81,74,78,72,80,3,No,Placed,4,1,7.2,No,2024-07-01
7,108,Meera,Female,20,Cyber Security,Kolkata,94,90,92,89,91,5,Yes,Placed,6,0,9.2,Yes,2024-07-03
8,109,Aditya,Male,21,Cloud Computing,Chennai,68,55,60,57,59,1,No,Not Placed,2,4,5.9,No,2024-07-05
9,110,Ishita,Female,22,AI & ML,Bangalore,88,82,85,84,87,4,Yes,Placed,5,0,8.4,Yes,2024-07-08
10,111,Rohan,Male,20,Data Science,Hyderabad,73,66,68,64,70,2,No,Not Placed,3,2,6.5,No,2024-07-10
11,112,Kavya,Female,23,Cloud Computing,Mumbai,91,87,89,86,88,4,Yes,Placed,5,0,8.8,Yes,2024-07-12
12,113,Yash,Male,21,Cyber Security,Pune,77,70,74,69,71,2,No,Not Placed,3,1,6.9,No,2024-07-15
13,114,Priya,Female,20,Data Science,Delhi,95,96,94,92,99,5,Yes,Placed,7,0,9.7,Yes,2024-07-18
14,115,Ritvik,Male,22,AI & ML,Kolkata,83,78,81,77,84,3,Yes,Placed,4,1,7.8,No,2024-07-20
15,116,Nisha,Female,21,Cyber Security,Chennai,87,80,83,82,85,4,Yes,Placed,5,0,8.3,Yes,2024-07-22
16,117,Karan,Male,23,Cloud Computing,Bangalore,65,58,61,55,60,1,No,Not Placed,2,3,5.8,No,2024-07-25
17,118,Shruti,Female,22,Data Science,Hyderabad,93,91,90,94,96,5,Yes,Placed,6,0,9.4,Yes,2024-07-28
18,119,Dev,Male,20,AI & ML,Mumbai,79,72,75,71,78,2,No,Placed,4,1,7.1,No,2024-07-30
19,120,Simran,Female,21,Cyber Security,Delhi,90,86,88,85,89,4,Yes,Placed,5,0,8.6,Yes,2024-08-01

## 4. Viewing the First Few Rows
The `head()` method displays the first 5 rows of the DataFrame by default. This is useful for quickly inspecting the data structure and content.

In [12]:
df.head()

,Student_ID,Name,Gender,Age,Department,City,Attendance_Percentage,Math_Marks,Science_Marks,English_Marks,Python_Marks,Projects_Completed,Internship,Placement_Status,Study_Hours_Per_Day,Backlogs,CGPA,Scholarship,Joining_Date
0,101,Aarav,Male,20,Data Science,Chennai,92,88,91,85,95,4,Yes,Placed,5,0,8.9,Yes,2024-06-12
1,102,Diya,Female,21,AI & ML,Bangalore,85,76,80,79,82,3,No,Not Placed,4,1,7.5,No,2024-06-15
2,103,Vihaan,Male,22,Cyber Security,Hyderabad,78,69,72,70,65,2,Yes,Placed,3,2,6.8,No,2024-06-18
3,104,Ananya,Female,20,Data Science,Mumbai,96,95,93,90,98,5,Yes,Placed,6,0,9.5,Yes,2024-06-20
4,105,Arjun,Male,23,Cloud Computing,Pune,70,60,65,58,62,1,No,Not Placed,2,3,6.1,No,2024-06-25

## 5. Viewing the Last Few Rows
The `tail()` method displays the last 5 rows of the DataFrame. This helps in understanding the end of the dataset.

In [13]:
df.tail()

,Student_ID,Name,Gender,Age,Department,City,Attendance_Percentage,Math_Marks,Science_Marks,English_Marks,Python_Marks,Projects_Completed,Internship,Placement_Status,Study_Hours_Per_Day,Backlogs,CGPA,Scholarship,Joining_Date
15,116,Nisha,Female,21,Cyber Security,Chennai,87,80,83,82,85,4,Yes,Placed,5,0,8.3,Yes,2024-07-22
16,117,Karan,Male,23,Cloud Computing,Bangalore,65,58,61,55,60,1,No,Not Placed,2,3,5.8,No,2024-07-25
17,118,Shruti,Female,22,Data Science,Hyderabad,93,91,90,94,96,5,Yes,Placed,6,0,9.4,Yes,2024-07-28
18,119,Dev,Male,20,AI & ML,Mumbai,79,72,75,71,78,2,No,Placed,4,1,7.1,No,2024-07-30
19,120,Simran,Female,21,Cyber Security,Delhi,90,86,88,85,89,4,Yes,Placed,5,0,8.6,Yes,2024-08-01

## 6. Getting the Total Number of Elements
`size` returns the total number of elements in the DataFrame (rows × columns). It's equivalent to `df.shape[0] * df.shape[1]`.

In [14]:
df.size

380

## 7. Getting the Shape of the DataFrame
`shape` returns a tuple representing the dimensions of the DataFrame: (number_of_rows, number_of_columns).

In [15]:
df.shape

(20, 19)

## 8. Getting Column Names
`columns` returns an Index object containing the column names of the DataFrame.

In [16]:
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Age', 'Department', 'City',
       'Attendance_Percentage', 'Math_Marks', 'Science_Marks', 'English_Marks',
       'Python_Marks', 'Projects_Completed', 'Internship', 'Placement_Status',
       'Study_Hours_Per_Day', 'Backlogs', 'CGPA', 'Scholarship',
       'Joining_Date'],
      dtype='str')

## 9. Unpacking Shape Information
This unpacks the tuple returned by `df.shape` into separate variables and prints them in a formatted string.

In [17]:
rows, columns = df.shape
print(f'Number of rows: {rows}')
print(f'Number of columns: {columns}')

Number of rows: 20
Number of columns: 19

## 10. Getting DataFrame Information
`info()` provides a concise summary of the DataFrame, including number of entries, column names and data types, number of non-null values, and memory usage.

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             20 non-null     int64
 1   Name                   20 non-null     str
 2   Gender                 20 non-null     str
 3   Age                    20 non-null     int64
 4   Department             20 non-null     str
 5   City                   20 non-null     str
 6   Attendance_Percentage  20 non-null     int64
 7   Math_Marks             20 non-null     int64
 8   Science_Marks          20 non-null     int64
 9   English_Marks          20 non-null     int64
 10  Python_Marks           20 non-null     int64
 11  Projects_Completed     20 non-null     int64
 12  Internship             20 non-null     str
 13  Placement_Status       20 non-null     str
 14  Study_Hours_Per_Day    20 non-null     int64
 15  Backlogs               20 non-null     int64
 16  CGPA                   20 non-null     float64
 17  Scholarship            20 non-null     str
 18  Joining_Date           20 non-null     str
dtypes: float64(1), int64(10), str(8)
memory usage: 3.1 KB

## 11. Statistical Summary (Numeric Columns)
`describe()` generates descriptive statistics for numeric columns, including count, mean, standard deviation, min, quartiles, and max.

In [19]:
df.describe()

,Student_ID,Age,Attendance_Percentage,Math_Marks,Science_Marks,English_Marks,Python_Marks,Projects_Completed,Study_Hours_Per_Day,Backlogs,CGPA
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,110.50000,21.250000,83.700000,77.850000,80.250000,77.350000,81.450000,3.200000,4.300000,0.950000,7.855000
std,5.91608,1.069924,9.454044,12.192642,10.769719,12.184006,12.894205,1.399248,1.454575,1.234376,1.260107
min,101.00000,20.000000,65.000000,55.000000,60.000000,55.000000,59.000000,1.000000,2.000000,0.000000,5.800000
25%,105.75000,20.000000,77.750000,69.750000,73.500000,69.750000,70.750000,2.000000,3.000000,0.000000,6.875000
50%,110.50000,21.000000,86.000000,79.000000,82.000000,80.500000,84.500000,3.500000,4.500000,0.500000,8.050000
75%,115.25000,22.000000,91.250000,87.250000,89.250000,86.500000,90.250000,4.000000,5.000000,1.250000,8.825000
max,120.00000,23.000000,96.000000,96.000000,94.000000,94.000000,99.000000,5.000000,7.000000,4.000000,9.700000

## 12. Data Types of Columns
`dtypes` returns the data type of each column in the DataFrame.

In [20]:
df.dtypes

Student_ID                 int64
Name                         str
Gender                       str
Age                        int64
Department                   str
City                         str
Attendance_Percentage      int64
Math_Marks                 int64
Science_Marks              int64
English_Marks              int64
Python_Marks               int64
Projects_Completed         int64
Internship                   str
Placement_Status             str
Study_Hours_Per_Day        int64
Backlogs                   int64
CGPA                     float64
Scholarship                  str
Joining_Date                 str
dtype: object

## 13. Statistical Summary (All Columns)
This provides descriptive statistics for all columns, including categorical data. For non-numeric columns, it shows count, unique values, top value, and frequency.

In [21]:
df.describe(include='all')

,Student_ID,Name,Gender,Age,Department,City,Attendance_Percentage,Math_Marks,Science_Marks,English_Marks,Python_Marks,Projects_Completed,Internship,Placement_Status,Study_Hours_Per_Day,Backlogs,CGPA,Scholarship,Joining_Date
count,20.00000,20,20,20.000000,20,20,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20,20,20.000000,20.000000,20.000000,20,20
unique,NaN,20,2,NaN,4,7,NaN,NaN,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,2,20
top,NaN,Aarav,Male,NaN,Data Science,Chennai,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Placed,NaN,NaN,NaN,Yes,2024-06-12
freq,NaN,1,10,NaN,6,4,NaN,NaN,NaN,NaN,NaN,NaN,12,14,NaN,NaN,NaN,10,1
mean,110.50000,NaN,NaN,21.250000,NaN,NaN,83.700000,77.850000,80.250000,77.350000,81.450000,3.200000,NaN,NaN,4.300000,0.950000,7.855000,NaN,NaN
std,5.91608,NaN,NaN,1.069924,NaN,NaN,9.454044,12.192642,10.769719,12.184006,12.894205,1.399248,NaN,NaN,1.454575,1.234376,1.260107,NaN,NaN
min,101.00000,NaN,NaN,20.000000,NaN,NaN,65.000000,55.000000,60.000000,55.000000,59.000000,1.000000,NaN,NaN,2.000000,0.000000,5.800000,NaN,NaN
25%,105.75000,NaN,NaN,20.000000,NaN,NaN,77.750000,69.750000,73.500000,69.750000,70.750000,2.000000,NaN,NaN,3.000000,0.000000,6.875000,NaN,NaN
50%,110.50000,NaN,NaN,21.000000,NaN,NaN,86.000000,79.000000,82.000000,80.500000,84.500000,3.500000,NaN,NaN,4.500000,0.500000,8.050000,NaN,NaN
75%,115.25000,NaN,NaN,22.000000,NaN,NaN,91.250000,87.250000,89.250000,86.500000,90.250000,4.000000,NaN,NaN,5.000000,1.250000,8.825000,NaN,NaN
max,120.00000,NaN,NaN,23.000000,NaN,NaN,96.000000,96.000000,94.000000,94.000000,99.000000,5.000000,NaN,NaN,7.000000,4.000000,9.700000,NaN,NaN

## Key Concepts Learned
1. **DataFrame Creation**: Loading data from CSV files
2. **Data Inspection**: Using `head()`, `tail()`, `shape`, `size`, `columns`
3. **Data Types**: Understanding column data types with `dtypes`
4. **Summary Statistics**: Generating insights with `describe()`
5. **DataFrame Info**: Getting overview with `info()`

## Next Steps
- Data cleaning and preprocessing
- Data manipulation (filtering, sorting, grouping)
- Data visualization
- Advanced Pandas operations

## Exercises
1. Try loading a different CSV file
2. Experiment with `df.head(10)` to see more rows
3. Use `df.describe()` on specific columns
4. Explore other DataFrame methods like `df.sample()` or `df.isnull().sum()`